class Column:

    GENRES = 'genres'
    RELEASE_DATE = 'release_date'
    DIRECTORS = 'directors'
    TYPE = 'type'
    YEAR = 'year'
    RUNTIME = 'runtime'
    NUM_OF_VOTES = 'num_of_votes'
    DATE_RATED = 'date_rated'
    URL = 'url'
    ID = 'id'
    TITLE = 'title'
    USER_RATING = 'user_rating'
    WEBSITE_RATING = 'website_rating'
    ACTOR_NAME = 'actor_name'
    ACTOR_ID = 'actor_id'
    DIRECTOR_ID = 'director_id'
    DIRECTOR_NAME = 'director_name'
    NAME = 'name '
