class IMDbColumn:
    IMDB_RATING = 'IMDb Rating'
    genres = 'Genres'
    NUM_VOTES = 'Num Votes'
    YEAR = 'Year'
    DIRECTORS = 'Directors'
    RELEASE_DATE = 'Release Date'
    URL = 'URL'
    TITLE = 'Title'
    YOUR_RATING = 'Your Rating'
    TITLE_TYPE = 'Title Type'
    RUNTIME = 'Runtime'
    CONST = 'Const'
    GENRES = 'Genres'
